### ISSUE TITLE
Can't run ./build.ksh with ksh93u+m

### ISSUE THREAD

**Issue by xplshn** [Projeto-Pindorama/copacabana#8]
I just built ksh93u+m, statically linked, default options, added the kshrc provided by them to /etc and then cloned this repo and tried to build:

![image](https://github.com/user-attachments/assets/c3b84f5a-54c3-410e-bd27-a619ac95d1d0)

I am on Andes/Alpine, which uses Busybox.

**Comment by takusuman** [comment]
Simple: mktemp wasn't installed.
I think the ``check/dependencies`` target may need to be run sooner, or maybe just don't use ``mktemp`` since we wouldn't need all this security just for some junk files.

**Comment by xplshn** [comment]
> Simple: mktemp wasn't installed. I think the `check/dependencies` target may need to be run sooner, or maybe just don't use `mktemp` since we wouldn't need all this security just for some junk files.

mktemp is installed tho.

![image](https://github.com/user-attachments/assets/e7ccbd27-82b7-4bf8-8e92-d160c74e7b65)


Where exactly is `mktemp` being used tho? So that I plug a a `set -v` or maybe a `set -x` there.

**Comment by takusuman** [comment]
Strange... Maybe check the PATH?

> Where exactly is mktemp being used tho? So that I plug a a set -v or maybe a set -x there.

It's used to create the ``$trash`` directory.

**Comment by xplshn** [comment]
![image](https://github.com/user-attachments/assets/0aa0b02b-5aea-4d56-b0d8-735947fe09b4)

**Comment by takusuman** [comment]
It's the most jokingly-said phrase possible, but "it works on my machine".

**Comment by xplshn** [comment]
Can I set the "trash" env to point to a local dir or smth?

**Comment by xplshn** [comment]
> It's the most jokingly-said phrase possible, but "it works on my machine".

Would you mind doing a `git diff origin/master` to check if your local repo differs from the remote? If so, would you also mind sharing a .tar of it?

**Comment by takusuman** [comment]
Sure, just edit out the build.ksh file. It's pretty readable because I wanted to keep it just as a set of instructions.

**Comment by takusuman** [comment]
> > It's the most jokingly-said phrase possible, but "it works on my machine".
> 
> Would you mind doing a `git diff origin/master` to check if your local repo differs from the remote? If so, would you also mind sharing a .tar of it?

Sure. Give me one minute.

**Comment by takusuman** [comment]
The only thing that differs here is the header of ``helpers.shi``:

```console
$ git diff origin/copaclang  
diff --git a/build-system/internals/helpers.shi b/build-system/internals/helpers.shi
index 40e6db2..8b0dfbe 100644
--- a/build-system/internals/helpers.shi
+++ b/build-system/internals/helpers.shi
@@ -1,5 +1,5 @@
 # vim: set filetype=sh :
-# Internal helper library for the Copacabana build system.
+# General helper library for the Copacabana build system.
 # Meant to be used with Korn Shell 93.
 #
 # Copyright (c) 2023-2024 Pindorama
diff --git a/packages b/packages
--- a/packages
+++ b/packages
@@ -1 +1 @@
-Subproject commit 97f5592f3e815e832621fbd4117f61cc74aecacd
+Subproject commit 97f5592f3e815e832621fbd4117f61cc74aecacd-dirty
```

Are you cloning from the ``copaclang`` branch?

**Comment by xplshn** [comment]
> The only thing that differs here is the header of `helpers.shi`:
> 
> ```
> $ git diff origin/copaclang  
> diff --git a/build-system/internals/helpers.shi b/build-system/internals/helpers.shi
> index 40e6db2..8b0dfbe 100644
> --- a/build-system/internals/helpers.shi
> +++ b/build-system/internals/helpers.shi
> @@ -1,5 +1,5 @@
>  # vim: set filetype=sh :
> -# Internal helper library for the Copacabana build system.
> +# General helper library for the Copacabana build system.
>  # Meant to be used with Korn Shell 93.
>  #
>  # Copyright (c) 2023-2024 Pindorama
> diff --git a/packages b/packages
> --- a/packages
> +++ b/packages
> @@ -1 +1 @@
> -Subproject commit 97f5592f3e815e832621fbd4117f61cc74aecacd
> +Subproject commit 97f5592f3e815e832621fbd4117f61cc74aecacd-dirty
> ```
> 
> Are you cloning from the `copaclang` branch?

That's the default branch, right? I used `git clone URL`, I didn't add `-b`

EDIT: `git branch` yields `copaclang`. So, yes.

**Comment by takusuman** [comment]
> Sure, just edit out the build.ksh file. It's pretty readable because I wanted to keep it just as a set of instructions.

It's defined here:
https://github.com/Projeto-Pindorama/copacabana/blob/766d46588f472ee9f80a7b6b2f1fcf8a7d126334/build.ksh#L29

**Comment by takusuman** [comment]
> That's the default branch, right? I used `git clone URL`, I didn't add `-b`

Yes, it is, but you can check with ``git branch`` and see if you're on it.

**Comment by xplshn** [comment]
I did, its `copaclang` on my end

**Comment by xplshn** [comment]
The issue is that you didn't use `mkdir -p` to create the directory mktemp is supposed to create the temp dir in. And also, think its better to define $TRASH_PREFIX on ./build.ksh instead of some internal helper, for readability's sake.

**Comment by takusuman** [comment]
> And also, think its better to define $TRASH_PREFIX on ./build.ksh instead of some internal helper, for readability's sake.

It's defined on a .INI file.

**Comment by xplshn** [comment]
Could you consider using the log_ functions defined here? I think they look more appealing than the current log output of ./build.ksh, but its a matter of personal taste. https://github.com/xplshn/Andes/blob/master/layout/etc/profile.d/std.sh

**Comment by xplshn** [comment]
> > And also, think its better to define $TRASH_PREFIX on ./build.ksh instead of some internal helper, for readability's sake.
> 
> It's defined on a .INI file.

Ahh, okay. Sorry then. My bad

**Comment by takusuman** [comment]
> The issue is that you didn't use `mkdir -p` to create the directory mktemp is supposed to create the temp dir in. And also, think its better to define $TRASH_PREFIX on ./build.ksh instead of some internal helper, for readability's sake.

Well, can I? I would, for sure.
I'm refactoring all of the build system and this part is bugging me.

**Comment by takusuman** [comment]
By the way, it currently doesn't compile anything, I will be rewriting the pkgbuild files at Alambiko and make some modifications here in my end.

**Comment by xplshn** [comment]
> By the way, it currently doesn't compile anything, I will be rewriting the pkgbuild files at Alambiko and make some modifications here in my end.

Ah... ah... I thought it, did..? I thought that it'd build a `rootfs` at least. Think `mkroot` from Toybox is a good starting point, you build with that and then you can swap out all of Toybox binaries with Heirloom, and leave only the `toybox` binaries that heirloom doesn't have (yet).

BTW: It isn't able to find `true`, which is a builtin, I used `bigdl add busybox/true` to explicitly add the true command as an external command into ~/.local/bin, which is part of my $PATH, but it didn't change much.
![image](https://github.com/user-attachments/assets/005ac554-9a85-4cb0-96ca-2949026c034e)

**Comment by takusuman** [comment]
> > By the way, it currently doesn't compile anything, I will be rewriting the pkgbuild files at Alambiko and make some modifications here in my end.
> 
> Ah... ah... I thought it, did..? I thought that it'd build a `rootfs` at least.

The [0.4. rootfs](http://pindorama.dob.jp/pub/Copacabana/0.4/) was made manually by me back in 2022, now I'm trying to automatize the process with all of this.

> Think `mkroot` from Toybox is a good starting point, you build with that and then you can swap out all of Toybox binaries with Heirloom, and leave only the `toybox` binaries that heirloom doesn't have (yet).

I have taken it in consideration to do pure cross-compiling of Copacabana. I'm just worried with some complex packages that we will have to deal with when making a desktop operating system, such as libdbus, pipewire, Xorg, KDE etc.

**Comment by takusuman** [comment]
> BTW: It isn't able to find true, which is a builtin, I used bigdl add busybox/true to explicitly add the true command as an external command into ~/.local/bin, which is part of my $PATH, but it didn't change much.

Weird.
Maybe I'm committing some of Sun's error with this, but this build-system isn't meant to be the most portable thing in the entire universe since I think only of building Copacabana from itself or from some other Linux system using at least some part of Copacabana's userland, that is, Heirloom NG, so I think most of these bugs can be avoided using Heirloom NG.

By the way, _maybe_ we can fix these anyway in the [platform checks](https://github.com/Projeto-Pindorama/copacabana/blob/copaclang/build-system/tasks/checks/platform.ksh), such as ``hash``ing ``true`` into ``busybox true`` if we end up finding busybox in the system.

**Comment by xplshn** [comment]
> > > By the way, it currently doesn't compile anything, I will be rewriting the pkgbuild files at Alambiko and make some modifications here in my end.
> > 
> > 
> > Ah... ah... I thought it, did..? I thought that it'd build a `rootfs` at least.
> 
> The [0.4. rootfs](http://pindorama.dob.jp/pub/Copacabana/0.4/) was made manually by me back in 2022, now I'm trying to automatize the process with all of this.
> 
> > Think `mkroot` from Toybox is a good starting point, you build with that and then you can swap out all of Toybox binaries with Heirloom, and leave only the `toybox` binaries that heirloom doesn't have (yet).
> 
> I have taken it in consideration to do pure cross-compiling of Copacabana. I'm just worried with some complex packages that we will have to deal with when making a desktop operating system, such as libdbus, pipewire, Xorg, KDE etc.

Oh. I thought that you weren't going to ship those until v2 or later. Check out iglunix, GNU-less Linux distro, great amount of packages for what it is. Its all MUSL.

I think `KDE` is a bit overkill, maybe Trinity would appeal more to the kind of people who would use a Linux distro with utilities originally made by `Sun Microsystems`. Or maybe no desktop at all (me), or maybe no graphical environment at all (me)...

About Pipewire and libdbus: Those could be built using libudev-zero, to avoid systemd's BS, specially on Musl, where nothing made by them works as its supposed to. (does systemd ever work as its supposed to?)

Anyways; I think shipping a few WMs and letting the user choose which one would be the best approach. You could make .AppBundles from an Alpine install and ship those along with MESA so that the user has a test environment to look around the system.

**Comment by xplshn** [comment]
> > BTW: It isn't able to find true, which is a builtin, I used bigdl add busybox/true to explicitly add the true command as an external command into ~/.local/bin, which is part of my $PATH, but it didn't change much.
> 
> Weird. Maybe I'm committing some of Sun's error with this, but this build-system isn't meant to be the most portable thing in the entire universe since I think only of building Copacabana from itself or from some other Linux system using at least some part of Copacabana's userland, that is, Heirloom NG, so I think most of these bugs can be avoided using Heirloom NG.
> 
> By the way, _maybe_ we can fix these anyway in the [platform checks](https://github.com/Projeto-Pindorama/copacabana/blob/copaclang/build-system/tasks/checks/platform.ksh), such as `hash`ing `true` into `busybox true` if we end up finding busybox in the system.

No need. Making it POSIX would be the best to ensure that it builds on POSIX systems... Comparing heirloom to other utils will uncover bugs in heirloom, so that's, good...

**Comment by takusuman** [comment]
> I think KDE is a bit overkill, maybe Trinity would appeal more to the kind of people who would use a Linux distro with utilities originally made by Sun Microsystems. Or maybe no desktop at all (me), or maybe no graphical environment at all (me)...

Well, the question is that I want to give options in the same measure that things keep formalized.
I want to ship KDE as the default desktop environment, but also have an option to install Enlightenment 16 as a simple window manager *or* to install the system with nothing beside its base; all of these can be decided on the install.
I like Trinity, but KDE have gotten better optimized lately (since at least 2020) and it provides a pretty much plain experience as an UNIX desktop.
Anyway, we still have to make dbus, pipewire and such work because other software may depend on these.

**Comment by takusuman** [comment]
> No need. Making it POSIX would be the best to ensure that it builds on POSIX systems... Comparing heirloom to other utils will uncover bugs in heirloom, so that's, good...

The biggest problem here is that I've abused "booleans" (``/bin/true`` and ``/bin/false``) instead of using integers or more portable measures.
I think these can be fixed per using a compatibility fix on the platform checks, though.

**Comment by xplshn** [comment]
> > I think KDE is a bit overkill, maybe Trinity would appeal more to the kind of people who would use a Linux distro with utilities originally made by Sun Microsystems. Or maybe no desktop at all (me), or maybe no graphical environment at all (me)...
> 
> Well, the question is that I want to give options in the same measure that things keep formalized. I want to ship KDE as the default desktop environment, but also have an option to install Enlightenment 16 as a simple window manager _or_ to install the system with nothing beside its base; all of these can be decided on the install. I like Trinity, but KDE have gotten better optimized lately (since at least 2020) and it provides a pretty much plain experience as an UNIX desktop. Anyway, we still have to make dbus, pipewire and such work because other software may depend on these.

As long as these never become part of base... (dbus, pipewire, *udev)
I think `mdev` does the work just fine and `libudev-zero` can be installed as a dependency of wayland things by the packages of `kde`, etc.

Also, I suggest not trying to package the `world` (everything out there), because it'd be lots of time/work, and I think what currently needs attention is the `base` itself.

For now, if you want to do a base and graphical release, you could ship a single-file GUI environment, like I have:
![image](https://github.com/user-attachments/assets/30ebbfdf-b805-4b70-92ec-71360330b5d2)
The only thing I have added to my system is this file + the config file of sway and the mesa package. The .blob/.AppBundle can be generated from an Alpine Linux install (since its small, and lots of its packages are using -static libraries where possible, also, its `musl` based, so the .AppBundles/.blobs are lighter.)

**Comment by xplshn** [comment]
> > No need. Making it POSIX would be the best to ensure that it builds on POSIX systems... Comparing heirloom to other utils will uncover bugs in heirloom, so that's, good...
> 
> The biggest problem here is that I've abused "booleans" (`/bin/true` and `/bin/false`) instead of using integers or more portable measures. I think these can be fixed per using a compatibility fix on the platform checks, though.

I think staying withing `$0` and avoiding calls to external programs as much as possible is the way to go. See [the pure sh bible](https://github.com/dylanaraps/pure-sh-bible), it also enhances readability to create constructs/function to replace external commands/shorten other constructs, such as: ifXdo (a call to `[ $X ] && "$@"`)

**Comment by takusuman** [comment]
> As long as these never become part of base... (dbus, pipewire, *udev)

You can rest assured: it won't.
The main reason of me creating Copacabana was to understand how to build a better future learning with a past that was forgotten in books and old UNIX systems, but also not ignoring necessities of the present.
Just like CDE didn't became inherent part of Solaris, AIX nor any other UNIX systems when it came out, KDE won't become inherent part of Copacabana's base system, it's just part of the (yet theoretical) ``desktop.tar.xz`` stage.

**Comment by xplshn** [comment]
> > As long as these never become part of base... (dbus, pipewire, *udev)
> 
> You can rest assured: it won't. The main reason of me creating Copacabana was to understand how to build a better future learning with a past that was forgotten in books and old UNIX systems, but also not ignoring necessities of the present. Just like CDE didn't became inherent part of Solaris, AIX nor any other UNIX systems when it came out, KDE won't become inherent part of Copacabana's base system, it's just part of the (yet theoretical) `desktop.tar.xz` stage.

Have you considered `sets` for packages with lots of dependencies, such as `kde`? I think you could take a look at the Illumos-based system `Tribblix`, which uses a very simple yet great, in my opinion, approach to package management.

EDIT: Tribblix calls them 'overlays', not `sets`. LINK: http://www.tribblix.org/overlays.html

**Comment by takusuman** [comment]
> For now, if you want to do a base and graphical release, you could ship a single-file GUI environment, like I have

That's really interesting for other reasons, but for the environment I would like to start "proto-packaging" things like it will be on pacote.
I don't think pacote will be done until the end of this month, but at least we can start generating tarballs for each package.

**Comment by takusuman** [comment]
> Have you considered sets for packages with lots of dependencies, such as kde? I think you could take a look at the Illumos-based system Tribblix, which uses a very simple yet great, in my opinion, approach to package management.

Sure! I've thought about these alone, but later I had seen what Tribblix does.
The best part is the fact that it uses a SVR4-esque package managenment, so we would still use pacote in the base of it.

**Comment by takusuman** [comment]
> I think staying withing `$0` and avoiding calls to external programs as much as possible is the way to go. See [the pure sh bible](https://github.com/dylanaraps/pure-sh-bible), it also enhances readability to create constructs/function to replace external commands/shorten other constructs, such as: ifXdo (a call to `[ $X ] && "$@"`)

I've taken KornShell 93 exactly for this reason, mostly because it provides many things that in POSIX are nonexistent and that would need to be mimicked by external programs.

To address this issue of ``true``/``false``, maybe we could create an ``Bool()`` function that check whether it's false or true.

**Comment by xplshn** [comment]
I'm closing because the issue is on my end. I was trying to build `copaclang` without using a heirloom-ng `$PATH`. I haven't tested that yet. But I'll close the issue.

**Comment by xplshn** [comment]
> > I think staying withing `$0` and avoiding calls to external programs as much as possible is the way to go. See [the pure sh bible](https://github.com/dylanaraps/pure-sh-bible), it also enhances readability to create constructs/function to replace external commands/shorten other constructs, such as: ifXdo (a call to `[ $X ] && "$@"`)
> 
> I've taken KornShell 93 exactly for this reason, mostly because it provides many things that in POSIX are nonexistent and that would need to be mimicked by external programs.
> 
> To address this issue of `true`/`false`, maybe we could create an `Bool()` function that check whether it's false or true.

Makes sense. I was going to suggest Go instead of SH scripting. But then realized that had it not been because this is shell I wouldn't have been able to correct the mktemp line so easily, test again, modify and test again.

**Comment by takusuman** [comment]
I think some ideas here are interesting, you can move something to a new issue if you wish to. I'm a little bit occupied working on the build system right now, but I will re-read the issue later and open a new issue for some of the advices you've given.

**Comment by takusuman** [comment]
> I was going to suggest Go instead of SH scripting.

Compiling a program to call a compiler to compile other programs sounds insane, I think shell is the way to go in this specific case, using plain and readable shell scripts, just like the AT&T crew would've done or Sun did until being sold to Oracle.
Many scripts here are still clumsy, so some refactor and more boilerplate (or façade) functions may be needed.

> But then realized that had it not been because this is shell I wouldn't have been able to correct the mktemp line so easily, test again, modify and test again.

I've said that to some people before, really nice to have a second opinion.

**Comment by xplshn** [comment]
> I think some ideas here are interesting, you can move something to a new issue if you wish to. I'm a little bit occupied working on the build system right now, but I will re-read the issue later and open a new issue for some of the advices you've given.

Okay, excellent! I'm going to do some work with `bigdl`. A complete overhaul is underway.

**Comment by xplshn** [comment]
@takusuman Could you simply do `"$DIR_PREFIX/$DIR_WHATEVER"` so that it works with the POSIX mktemp? ("" is escaped in a `'`, commands should treat the "" as part of the filename when they are inside of a `'`).
```
]~/Documents/ItAll/copacabana< ./build.ksh
+ progname=build.ksh
+ dirname build.ksh
+ cd .
+ pwd -P
+ progdir=/home/anto/Documents/ItAll/copacabana
+ tasks=/home/anto/Documents/ItAll/copacabana/build-system/tasks
+ . /home/anto/Documents/ItAll/copacabana/build-system/internals/makier.ksh
+ _make checks/platform
+ lang=.ksh
+ tasks=/home/anto/Documents/ItAll/copacabana/build-system/tasks
+ tak=checks/platform
+ shift
+ printf %s/%s%s /home/anto/Documents/ItAll/copacabana/build-system/tasks checks/platform .ksh
+ . /home/anto/Documents/ItAll/copacabana/build-system/tasks/checks/platform.ksh $'\'\''
+ . /home/anto/Documents/ItAll/copacabana/build-system/internals/posix-alt.shi
+ . /home/anto/Documents/ItAll/copacabana/build-system/internals/log.shi
+ . /home/anto/Documents/ItAll/copacabana/build-system/internals/helpers.shi
+ BUILD_KSH=true
+ readonly BUILD_KSH
+ nawk '{ gsub("-", ""); print $NF; }'
+ printf %s 'Version AJM 93u+m/1.1.0-alpha+fa0ee840 2024-07-31'
+ KSH93_RELEASE=20240731
+ readonly KSH93_RELEASE
+ export BUILD_KSH KSH93_RELEASE
+ . /home/anto/Documents/ItAll/copacabana/build-system/internals/rconfig.shi
+ . /home/anto/Documents/ItAll/copacabana/build-system/internals/disks.shi
+ rconfig /home/anto/Documents/ItAll/copacabana/build-system/machine.ini
+ rconfig /home/anto/Documents/ItAll/copacabana/build-system/work.ini
+ rconfig /home/anto/Documents/ItAll/copacabana/build-system/fhs.ini
+ mktemp -d '"/tmp"/CopaBuild.XXXXXX'
mktemp: No such file or directory
+ trash=''
]~/Documents/ItAll/copacabana<
```

**Comment by takusuman** [comment]
Good night.
Pardon for the delay, let me see what I can do.

**Comment by takusuman** [comment]
I think that happened because of the new INI parser "bullet-proofing", I will fix that as soon as possible.

**Comment by takusuman** [comment]
> As long as these never become part of base... (dbus, pipewire, *udev)

I was going to ask: what about OpenPAM/LinuxPAM? Does it go in the base? I've been thinking about this lately.

**Comment by xplshn** [comment]
> > As long as these never become part of base... (dbus, pipewire, *udev)
> 
> I was going to ask: what about OpenPAM/LinuxPAM? Does it go in the base? I've been thinking about this lately.

Have you seen how Gentoo has a SElinux & an Apparmor version? I think that the kernel and other closely related things such as the security blanket used and the PAM implementation that pair it should be in a different set as `base`, but maybe this adds more complexity... Still, if it is kept separated, that means that in the future, you'll have the flexibility to offer other configurations/options, just like Gentoo

**Comment by takusuman** [comment]
> Still, if it is kept separated, that means that in the future, you'll have the flexibility to offer other configurations/options, just like Gentoo

I want to kind of keep it as uniform because of stability, so reporting failures and bugs is easier than a system that you build completely from scratch. My thought on this is to have the stability that one would find in classic Solaris, SunOS, IRIX, etc.
I know that PAM is complex, but OpenPAM may be a palliative to it since it's considered simpler compared to LinuxPAM (as long as I've read). Anyway, I want to avoid linking some vital system utilities to it, such as the ``/sbin/login`` program.

**Comment by xplshn** [comment]
OpenPAM as the default then I suppose. You should look at the work of Iglunix & Glauccus, both distros could be considered Linux based OSes and not GNU/Linux distributions
